In [1]:
import numpy as np
from numpy import linalg as LA
def getMatrixDeternminant2(m):
    #base case for 2x2 matrix
    if len(m) == 2:
        return m[0][0]*m[1][1]-m[0][1]*m[1][0]

    determinant = 0
    for c in range(len(m)):
        determinant += ((-1)**c)*m[0][c]*getMatrixDeternminant2(getMatrixMinor2(m,0,c))
    return determinant

def getMatrixMinor2(arr,i,j):
    # ith row, jth column removed
    return arr[np.array(list(range(i))+list(range(i+1,arr.shape[0])))[:,np.newaxis],
               np.array(list(range(j))+list(range(j+1,arr.shape[1])))]

def getMatrixInverse2(m):
    determinant = getMatrixDeternminant2(m)
#     special case for 2x2 matrix:
    if len(m) == 2:
        return [[m[1][1]/determinant, -1*m[0][1]/determinant],
                [-1*m[1][0]/determinant, m[0][0]/determinant]]

#   find matrix of cofactors:
    cofactors=np.zeros((len(m),len(m[0])), dtype=float)
    for r in range(len(m)):
        for c in range(len(m)):
            minor = getMatrixMinor2(m,r,c)
            cofactors[r][c]=(((-1)**(r+c)) * getMatrixDeternminant2(minor))
#   transpose cofactor=>adj
    checked=np.zeros((len(m),len(m[0])), dtype=int)
    for i in range(len(m)):
        for j in range(len(m)):
            if(checked[i][j]==0 & i!=j):
                temp=cofactors[i][j]
                cofactors[i][j]=cofactors[j][i]
                cofactors[j][i]=temp
                checked[i][j]=1
                checked[j][i]=1
#   adj*det**(-1)
    for r in range(len(cofactors)):
        for c in range(len(cofactors)):
            cofactors[r][c] = cofactors[r][c]/determinant

    return cofactors

In [5]:
arr = np.array([[1,1,1,1],[2,1,-1,-2],[1,-1,-1,1],[1,-2,2,-1]])
w, p = LA.eig(arr)
for i in range(len(w)):
    print("\u03BB={eigenvelue} p{key}={eigenvector}".format(eigenvelue=w[i],key=i+1,eigenvector=p[:,i]))
print('\nP=',p)

λ=2.8284271247461894 p1=[-0.15622986  0.68963195 -0.37717224 -0.59811462]
λ=2.236067977499789 p2=[ 0.69455348 -0.13264791  0.42925766  0.56190557]
λ=-2.828427124746192 p3=[-0.37717224  0.59811462  0.15622986  0.68963195]
λ=-2.23606797749979 p4=[ 0.42925766 -0.56190557 -0.69455348 -0.13264791]

P= [[-0.15622986  0.69455348 -0.37717224  0.42925766]
 [ 0.68963195 -0.13264791  0.59811462 -0.56190557]
 [-0.37717224  0.42925766  0.15622986 -0.69455348]
 [-0.59811462  0.56190557  0.68963195 -0.13264791]]


In [3]:
p_inverse=getMatrixInverse2(p)
print("P^(-1)=",p_inverse)

P^(-1)= [[ 0.75434448  1.06680419 -0.31245971 -0.44188477]
 [ 1.25645904  0.56190557  0.29660975  0.13264791]
 [-0.31245971  0.44188477 -0.75434448  1.06680419]
 [ 0.29660975 -0.13264791 -1.25645904  0.56190557]]


In [9]:
D=np.dot(np.dot(p_inverse,arr),p)
a=np.diag(D) #get D matrix's diagnal element
D=np.diag(a) #transfer diagnal element to a new 4*4 matrix
with np.printoptions(precision=5): 
    print("D=",D)
#--------------------------------------------#

D_100=D
for i in range(len(D_100)):
    D_100[i][i]=pow(D_100[i][i],100)

result=np.zeros((4,4), dtype=float)
for i in range(4):
    for j in range(4):
        for k in range(4):
            result[i][j] += p[i][k] * D_100[k][j]
#result=P mutilply D^100
result2=np.zeros((4,4), dtype=float)
for i in range(4):
    for j in range(4):
        for k in range(4):
            result2[i][j] += result[i][k] * p_inverse[k][j]
#result2=P mutilply D^100 result mutilply P_inverse
print("A^100=",result2)

D= [[ 2.82843  0.       0.       0.     ]
 [ 0.       2.23607  0.       0.     ]
 [ 0.       0.      -2.82843  0.     ]
 [ 0.       0.       0.      -2.23607]]
A^100= [[ 8.88151388e+34 -4.75749231e+44  4.75749231e+44 -4.75749231e+44]
 [ 4.75749231e+44  1.42724769e+45 -9.51498462e+44  4.75749231e+44]
 [-4.75749231e+44 -4.75749231e+44  8.88203058e+34  4.75749231e+44]
 [-9.51498462e+44 -4.75749231e+44 -4.75749231e+44  1.42724769e+45]]


NameError: name 'array' is not defined