In [8]:
import numpy as np
def getMatrixDeternminant2(m):
    #base case for 2x2 matrix
    if len(m) == 2:
        return m[0][0]*m[1][1]-m[0][1]*m[1][0]

    determinant = 0
    for c in range(len(m)):
        determinant += ((-1)**c)*m[0][c]*getMatrixDeternminant2(getMatrixMinor2(m,0,c))
    return determinant

def getMatrixMinor2(arr,i,j):
    # ith row, jth column removed
    return arr[np.array(list(range(i))+list(range(i+1,arr.shape[0])))[:,np.newaxis],
               np.array(list(range(j))+list(range(j+1,arr.shape[1])))]

def getMatrixInverse2(m):
    determinant = getMatrixDeternminant2(m)
#     special case for 2x2 matrix:
    if len(m) == 2:
        return [[m[1][1]/determinant, -1*m[0][1]/determinant],
                [-1*m[1][0]/determinant, m[0][0]/determinant]]

#   find matrix of cofactors:
    cofactors=np.zeros((len(m),len(m[0])), dtype=float)
    for r in range(len(m)):
        for c in range(len(m)):
            minor = getMatrixMinor2(m,r,c)
            cofactors[r][c]=(((-1)**(r+c)) * getMatrixDeternminant2(minor))
#   transpose cofactor=>adj
    checked=np.zeros((len(m),len(m[0])), dtype=int)
    for i in range(len(m)):
        for j in range(len(m)):
            if(checked[i][j]==0 & i!=j):
                temp=cofactors[i][j]
                cofactors[i][j]=cofactors[j][i]
                cofactors[j][i]=temp
                checked[i][j]=1
                checked[j][i]=1
#   adj*det**(-1)
    for r in range(len(cofactors)):
        for c in range(len(cofactors)):
            cofactors[r][c] = cofactors[r][c]/determinant

    return cofactors

In [9]:
print(">Input matrix dimensions:")
a,b = map(int,input().split())
print("\n>Input matrix:")
list1=[]
for i in range(a):
    a = list(map(float,input().strip().split()))[:b]
    list1.append(a)
array= np.array(list1)
print("\n>InverseMatrix:")
print(getMatrixInverse2(array))

>Input matrix dimensions:
4 4

>Input matrix:
2 2 5 3.5 
-2 -2 5 12
6 6 15 9
4 3 2 1

>InverseMatrix:
[[-9.5         0.55        2.85        1.        ]
 [14.         -0.8        -4.26666667 -1.        ]
 [-3.          0.1         1.03333333 -0.        ]
 [ 2.          0.         -0.66666667  0.        ]]


In [20]:
# arr = np.array([[1,-1,-2],[2,-3,-5],[-1,3,5]])
# arr2 = np.array([2,2,5,3.5],[-2,-2,5,12],[6,6,15,9],[4,3,2,1])
# print(getMatrixInverse2(arr))
# getMatrixDeternminant2(arr)
# print(len(arr))
# print(type(arr))
# print(getMatrixInverse2(array))


[[-0.  1.  1.]
 [ 5. -3. -1.]
 [-3.  2.  1.]]
