In [27]:
from mat4py import loadmat
import numpy as np
data = loadmat('Project01_data.mat')

In [41]:
a=np.array(data['A'])
print("A=")
print(a)
b=np.array(data['B'])
print("B=")
print(b)

A=
[[  0.4976 -16.      -9.      10.      16.      -2.    ]
 [  0.058  -11.      16.       0.      13.      17.    ]
 [  0.9783   4.       1.      10.     -11.      10.    ]
 [  0.0246  11.       3.     -16.      17.      -6.    ]
 [  0.1509 -13.     -19.       1.      -2.       1.    ]
 [  0.6284 -15.     -15.      -1.      -3.       9.    ]]
B=
[[-16.      -9.      10.      16.      -2.       0.1066]
 [-11.      16.       0.      13.      17.       0.4511]
 [  4.       1.      10.     -11.      10.       0.1943]
 [ 11.       3.     -16.      17.      -6.       0.8257]
 [-13.     -19.       1.      -2.       1.       0.1856]
 [-15.     -15.      -1.      -3.       9.       0.0642]]


In [42]:
result=np.zeros((6,6), dtype=float)
for i in range(len(a)):
    for j in range(len(a[0])):
        for k in range(len(a[0])):
            result[i][j] += a[i][k] * b[k][j]
print("A*B=")           
print(result)

A*B=
[[  64.0384     -513.4784     -227.024        42.9616     -424.9952
     2.18494416]
 [-239.928      -662.522       156.58       -395.072       138.884
     1.6570828 ]
 [  47.3472      145.1953     -161.217       218.6528       95.0434
     8.96038678]
 [-416.3936     -102.2214      309.246      -177.6064      275.9508
    -4.89357764]
 [  86.5856     -202.3581     -207.491        60.4144     -410.3018
    -9.02121406]
 [ -12.0544     -341.6556     -139.716       -57.9456     -322.2568
   -10.41871256]]


In [40]:
import numpy as np
z=np.array(data['Z'])
z=z.astype(float)
for i in range(10):
    if z[i][i] == 0.0:
        sys.exit('Divide by zero detected!')
        
    for j in range(10):
        if i != j:
            ratio = z[j][i]/z[i][i]

            for k in range(11):
                z[j][k] = z[j][k] - ratio * z[i][k]
for i in range(10):
    z[i][10]=z[i][10]/z[i][i]
    z[i][i]/=z[i][i]
    
for row in z:
    print (row)

[ 1.00000000e+00 -8.88178420e-16  6.08451941e-12 -4.34586208e-11
  1.25423413e-11  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  6.84778043e+04]
[ 0.00000000e+00  1.00000000e+00  2.79377838e-12 -1.99553154e-11
  5.75954452e-12  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  4.02480955e+04]
[ 0.00000000e+00  0.00000000e+00  1.00000000e+00  5.38912898e-11
 -1.55537092e-11  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  7.46506939e+04]
[ 0.00000000e+00  0.00000000e+00 -1.95509024e-12  1.00000000e+00
 -4.03029209e-12  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  3.23069879e+04]
[ 0.00000000e+00  0.00000000e+00  1.04153449e-11 -7.43989657e-11
  1.00000000e+00  3.55271368e-15  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  5.37995739e+04]
[ 0.00000000e+00  0.00000000e+00  4.66849786e-12 -3.33468974e-11
  9.62417568e-12  1.00000000e+00  0