In [1]:
import numpy as np
from numpy import linalg as LA
def getMatrixDeternminant2(m):
    #base case for 2x2 matrix
    if len(m) == 2:
        return m[0][0]*m[1][1]-m[0][1]*m[1][0]

    determinant = 0
    for c in range(len(m)):
        determinant += ((-1)**c)*m[0][c]*getMatrixDeternminant2(getMatrixMinor2(m,0,c))
    return determinant

def getMatrixMinor2(arr,i,j):
    # ith row, jth column removed
    return arr[np.array(list(range(i))+list(range(i+1,arr.shape[0])))[:,np.newaxis],
               np.array(list(range(j))+list(range(j+1,arr.shape[1])))]

def getMatrixInverse2(m):
    determinant = getMatrixDeternminant2(m)
#     special case for 2x2 matrix:
    if len(m) == 2:
        return [[m[1][1]/determinant, -1*m[0][1]/determinant],
                [-1*m[1][0]/determinant, m[0][0]/determinant]]

#   find matrix of cofactors:
    cofactors=np.zeros((len(m),len(m[0])), dtype=float)
    for r in range(len(m)):
        for c in range(len(m)):
            minor = getMatrixMinor2(m,r,c)
            cofactors[r][c]=(((-1)**(r+c)) * getMatrixDeternminant2(minor))
#   transpose cofactor=>adj
    checked=np.zeros((len(m),len(m[0])), dtype=int)
    for i in range(len(m)):
        for j in range(len(m)):
            if(checked[i][j]==0 & i!=j):
                temp=cofactors[i][j]
                cofactors[i][j]=cofactors[j][i]
                cofactors[j][i]=temp
                checked[i][j]=1
                checked[j][i]=1
#   adj*det**(-1)
    for r in range(len(cofactors)):
        for c in range(len(cofactors)):
            cofactors[r][c] = cofactors[r][c]/determinant

    return cofactors

def IsLinearIndependent(m):
    if(getMatrixDeternminant2(m)==0):
        print("InputError : Matrix A must be linearly independent columns!")

def norm_square(k):
    total=0.0
    for i in range(len(k)):
        total+=np.square(k[i])
    return total
    
def inner_product(A,B):
    for i in range(len(A)):
        total+=A[i]*B[i]
    return total

def normalize(A):
    for i in range(len(A[0])):
        norm=np.linalg.norm(A[:, i])
        A[:,i]/=norm
    return A

def gram_Schmidt(A):
    n=A.shape[1]
    for j in range(n):
        ba=np.array(A[:,j])
        for k in range(j):
            A[:,j]=A[:,j]-(np.dot(A[:, k],ba)* A[:, k])/norm_square(A[:,k]) 
    return A

def gram_Schmidt2(A):
    n=A.shape[1]
    a=np.array(A)
    for j in range(n):
        ba=np.array(a[:,j])
        for k in range(j):
            a[:,j]=a[:,j]-(np.dot(a[:, k],ba)* a[:, k])/norm_square(a[:,k]) 
    for i in range(len(a[0])):
        column = a[:,i]
        print(f'u{i} = ',column)
    return A

def QR_Decomposition(A):
    ba=np.array(A)
    q=np.array(normalize(gram_Schmidt(np.array(A))))
#     q=np.zeros((3,3)) 
    r=np.zeros((len(A),len(A[0])))
    print("\nQ=",q)
    for i in range(len(A)):
        for j in range(len(A[0])):
            r[i][j]=np.dot(q[:,j],ba[:,i])
    print(r)
    print("\nR=")
    for i in range(len(a[0])):
        column = r[:,i]
        print(column)

In [2]:
print(">Input the dimension of matrix A:")
a,b = map(int,input().split())
print("\n>Input matrix A:")
list1=[]
for i in range(a):
    a = list(map(float,input().strip().split()))[:b]
    list1.append(a)
array= np.array(list1)

IsLinearIndependent(array)

>Input the dimension of matrix A:
3 4 

>Input matrix A:
2 -2 6 4
2 -2 6 3
5 5 15 2
InputError : Matrix A must be linearly independent columns!


In [3]:
print(">Input the dimension of matrix A:")
a,b = map(int,input().split())
print("\n>Input matrix A:")
list1=[]
for i in range(a):
    a = list(map(float,input().strip().split()))[:b]
    list1.append(a)
array= np.array(list1)
# IsLinearIndependent(array)
# -----------------------------------------------
print("\n>Column vectors of A :")
for i in range(len(array[0])):
    column = array[:,i]
    print('u{}={}' .format(i,column))

>Input the dimension of matrix A:
3 3 

>Input matrix A:
1 0 0 
1 1 0
1 1 1

>Column vectors of A :
u0=[1. 1. 1.]
u1=[0. 1. 1.]
u2=[0. 0. 1.]


In [4]:
a=np.array(array)
print("\n>Orthogonal basis :")
gram_Schmidt(a)
for i in range(len(a[0])):
    column = a[:,i]
    print(f'u{i+1} = ',column)

print("\n>Orthonormal basis :")
normalize(a)
for i in range(len(a[0])):
    column = a[:,i]
    print(f'v{i+1} = ',column)

a=np.array(array)    #reset array A
Q=np.array(normalize(gram_Schmidt(np.array(a)))) #Q is orthonormal column vectors
R=np.zeros((len(a),len(a[0]))) #define array r
print("\n>QR :\nQ=",Q)
for i in range(len(a)): #
    for j in range(len(a[0])):
        R[i][j]=np.dot(Q[:,j],a[:,i])
print("\nR=",R)


>Orthogonal basis :
u1 =  [1. 1. 1.]
u2 =  [-0.66666667  0.33333333  0.33333333]
u3 =  [ 0.  -0.5  0.5]

>Orthonormal basis :
v1 =  [0.57735027 0.57735027 0.57735027]
v2 =  [-0.81649658  0.40824829  0.40824829]
v3 =  [ 0.         -0.70710678  0.70710678]

>QR :
Q= [[ 0.57735027 -0.81649658  0.        ]
 [ 0.57735027  0.40824829 -0.70710678]
 [ 0.57735027  0.40824829  0.70710678]]

R= [[1.73205081e+00 1.11022302e-16 0.00000000e+00]
 [1.15470054e+00 8.16496581e-01 0.00000000e+00]
 [5.77350269e-01 4.08248290e-01 7.07106781e-01]]


In [5]:
print("A =\n",Q.dot(R))

A =
 [[ 0.05719096 -0.66666667  0.        ]
 [ 1.06315623  0.0446582  -0.5       ]
 [ 1.87965281  0.62200847  0.5       ]]


In [7]:
print(">Input the dimension of matrix A:")
a,b = map(int,input().split())
print("\n>Input matrix A:")
list1=[]
for i in range(a):
    a = list(map(float,input().strip().split()))[:b]
    list1.append(a)
array2= np.array(list1)
# IsLinearIndependent(array)
# ------------------------------------------------------------------------
print("\n>Column vectors of A :")
for i in range(len(array2[0])):
    column = array2[:,i]
    print('u{}={}' .format(i,column))
    
a=np.array(array2)
print("\n>Orthogonal basis :")
gram_Schmidt(a)
for i in range(len(a[0])):
    column = a[:,i]
    print(f'u{i+1} = ',column)

print("\n>Orthonormal basis :")
normalize(a)
for i in range(len(a[0])):
    column = a[:,i]
    print(f'v{i+1} = ',column)
# --------------------------------QR----------------------------------------------:
a=np.array(array2)  #reset array A
Q=np.array(normalize(gram_Schmidt(np.array(a)))) #q is orthonormal column vectors
R=np.zeros((len(a[0]),len(a[0]))) #define array r
print("\n>QR :\nQ=",Q)
for i in range(len(a[0])):
    for j in range(len(a[0])):
        R[j][i]=np.dot(Q[:,j],a[:,i])
print("\nR=",R)

>Input the dimension of matrix A:
4 2

>Input matrix A:
-2 1
2 -8
1 0
0 1

>Column vectors of A :
u0=[-2.  2.  1.  0.]
u1=[ 1. -8.  0.  1.]

>Orthogonal basis :
u1 =  [-2.  2.  1.  0.]
u2 =  [-3. -4.  2.  1.]

>Orthonormal basis :
v1 =  [-0.66666667  0.66666667  0.33333333  0.        ]
v2 =  [-0.54772256 -0.73029674  0.36514837  0.18257419]

>QR :
Q= [[-0.66666667 -0.54772256]
 [ 0.66666667 -0.73029674]
 [ 0.33333333  0.36514837]
 [ 0.          0.18257419]]

R= [[ 3.         -6.        ]
 [ 0.          5.47722558]]


In [8]:
print("A =\n",Q.dot(R))

A =
 [[-2.00000000e+00  1.00000000e+00]
 [ 2.00000000e+00 -8.00000000e+00]
 [ 1.00000000e+00 -2.22044605e-16]
 [ 0.00000000e+00  1.00000000e+00]]
